### PR TITLE
Add List::Util::reductions

### PR DESCRIPTION
**Pull request by leonerd**
As requested in https://rt.cpan.org/Ticket/Display.html?id=128237

### CODE REVIEW

**Comment by dur-randir** [comment]
- it generates new compiler warning
- it leaks if code block dies

**Comment by leonerd** [comment]
@dur-randir Ahyes; the leak I can imagine where that comes from and I think I have an idea on fixing it. But what new warning is generated? I don't get anything from gcc - though it quite often doesn't complain.

**Comment by leonerd** [comment]
496d642 now handles destruction of accumulated temporaries after exceptions.

Still awaiting more detail on what the compiler warning is

**Comment by leonerd** [comment]
I believe this may be ready. @dur-randir any comment?

**Comment by dur-randir** [comment]
Since you already use AvARRAY, you could also use it to push items in the ST() manner, but otherwise it's fine.

**Pull request merged**
