### PR TITLE
Fix Perl 5.6.2 support

### PR DESCRIPTION
**Pull request by pali**

### CODE REVIEW

**Comment by pali** [comment]
Looks like Travis tests are not working anymore...

**Comment by pali** [comment]
@leonerd can you look at this PR?

**Comment by leonerd** [comment]
LGTM

**Comment by pali** [comment]
Thanks!

Anyway, can you re-enable Travis Continuous Integration which run unit tests for every push and every pull request? Because original repository name was renamed after https://github.com/Dual-Life/Scalar-List-Utils/pull/37 it is needed to enable Dual-Life on https://travis-ci.org/ again. See last comment from that #37.

**Comment by pali** [comment]
@leonerd can you release new version on cpan so Scalar::Util could be installed again on Perl 5.6.2? Scalar::Util is used by lot of modules and that would allow doing automatic testing...

Also can you re-enable Travis Continuous Integration?

**Comment by pali** [comment]
@leonerd Any news about new release or re-enabling Travis?

**Comment by leonerd** [comment]
1.49 now inbound to CPAN. Have poked the Dual-Life repo admins re. travis

**Pull request merged**
